//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TestView.rc
//

#define IDM_R_TREE_LOAD					40001
#define IDM_R_TREE_DISPLAY              40002
#define IDM_QUAD_TREE_LOAD              40011
#define IDM_QUAD_TREE_DISPLAY           40012
#define IDM_TEST_STORAGE				40021

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         40026
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
